services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: postwagens-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with file watching in Docker
    restart: always

  redis:
    image: redis:6
    container_name: postwagens-redis
    command: redis-server --requirepass admin123
    env_file:
      - ./backend/.env
    ports:
      - "6379:6379"
    restart: always

  cron:
    build:
      context: ./cron
      dockerfile: Dockerfile.dev
    container_name: postwagens-cron
    ports:
      - "5007:5007"
    volumes:
      - ./cron:/app
      - /app/node_modules
    env_file:
      - ./cron/.env
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with file watching in Docker
    restart: always

volumes:
  pgdata: